server:
  port: 9002
  tomcat:
    max-threads: 5
spring:
  application:
    name: service-02-api

  cloud:
    nacos:
      discovery:
        server-addr: nacos.yuhangma.com
        ip: 118.25.144.92