server:
  port: 9003
  tomcat:
    max-threads: 5
spring:
  application:
    name: service-02-api

  cloud:
    nacos:
      discovery:
        server-addr: 118.25.144.92:8848
#        ip: how to use dynamic ip addr?